apiVersion: apps/v1
kind: Deployment
metadata:
  name: uydrds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uydrds
  template:
    metadata:
      labels:
        app: uydrds
    spec:
      containers:
      - image: okteto.dev/uydrds:latest
        name: uydrds
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f5fa49ee-10f5-4149-9ff8-88b4a074359c"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "f5fa49ee-10f5-4149-9ff8-88b4a074359c"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
